using System;

namespace TSLPatcher.Core.Formats.NCS;

/// <summary>
/// Complete NCS instruction types combining bytecode and qualifier.
/// 
/// Each instruction type represents a specific operation with typed operands.
/// The tuple contains (ByteCode, Qualifier) for each instruction variant.
/// 
/// References:
///     vendor/xoreos/src/aurora/nwscript/ncsfile.h:86-280 - NCSFile instruction types
///     vendor/Kotor.NET/Kotor.NET/Formats/KotorNCS/NCS.cs:725-798 - Instruction definitions
///     https://github.com/xoreos/xoreos-docs - Torlack's NCS specification
/// </summary>
public enum NCSInstructionType
{
    /// <summary>Unknown/reserved instruction</summary>
    RESERVED,
    /// <summary>Variant with qualifier 0x01</summary>
    RESERVED_01,
    
    NOP,
    CPDOWNSP,
    RSADDI,
    RSADDF,
    RSADDS,
    RSADDO,
    RSADDEFF,
    RSADDEVT,
    RSADDLOC,
    RSADDTAL,
    CPTOPSP,
    CONSTI,
    CONSTF,
    CONSTS,
    CONSTO,
    ACTION,
    LOGANDII,
    LOGORII,
    INCORII,
    EXCORII,
    BOOLANDII,
    EQUALII,
    EQUALFF,
    EQUALSS,
    EQUALOO,
    EQUALTT,
    EQUALEFFEFF,
    EQUALEVTEVT,
    EQUALLOCLOC,
    EQUALTALTAL,
    NEQUALII,
    NEQUALFF,
    NEQUALSS,
    NEQUALOO,
    NEQUALTT,
    NEQUALEFFEFF,
    NEQUALEVTEVT,
    NEQUALLOCLOC,
    NEQUALTALTAL,
    GEQII,
    GEQFF,
    GTII,
    GTFF,
    LTII,
    LTFF,
    LEQII,
    LEQFF,
    SHLEFTII,
    SHRIGHTII,
    USHRIGHTII,
    ADDII,
    ADDIF,
    ADDFI,
    ADDFF,
    ADDSS,
    ADDVV,
    SUBII,
    SUBIF,
    SUBFI,
    SUBFF,
    SUBVV,
    MULII,
    MULIF,
    MULFI,
    MULFF,
    MULVF,
    MULFV,
    DIVII,
    DIVIF,
    DIVFI,
    DIVFF,
    DIVVF,
    DIVFV,
    MODII,
    NEGI,
    NEGF,
    COMPI,
    MOVSP,
    JMP,
    JSR,
    JZ,
    RETN,
    DESTRUCT,
    NOTI,
    DECxSP,
    INCxSP,
    JNZ,
    CPDOWNBP,
    CPTOPBP,
    DECxBP,
    INCxBP,
    SAVEBP,
    RESTOREBP,
    STORE_STATE,
    NOP2
}

/// <summary>
/// Extension methods for NCSInstructionType.
/// </summary>
public static class NCSInstructionTypeExtensions
{
    /// <summary>
    /// Get the bytecode and qualifier for this instruction type.
    /// </summary>
    public static (NCSByteCode ByteCode, byte Qualifier) GetValue(this NCSInstructionType type)
    {
        return type switch
        {
            NCSInstructionType.RESERVED => (NCSByteCode.RESERVED, 0x00),
            NCSInstructionType.RESERVED_01 => (NCSByteCode.RESERVED, 0x01),
            NCSInstructionType.NOP => (NCSByteCode.NOP, 0x00),
            NCSInstructionType.CPDOWNSP => (NCSByteCode.CPDOWNSP, 0x01),
            NCSInstructionType.RSADDI => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.RSADDF => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Float),
            NCSInstructionType.RSADDS => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.String),
            NCSInstructionType.RSADDO => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Object),
            NCSInstructionType.RSADDEFF => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Effect),
            NCSInstructionType.RSADDEVT => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Event),
            NCSInstructionType.RSADDLOC => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Location),
            NCSInstructionType.RSADDTAL => (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Talent),
            NCSInstructionType.CPTOPSP => (NCSByteCode.CPTOPSP, 0x01),
            NCSInstructionType.CONSTI => (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.CONSTF => (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.Float),
            NCSInstructionType.CONSTS => (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.String),
            NCSInstructionType.CONSTO => (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.Object),
            NCSInstructionType.ACTION => (NCSByteCode.ACTION, 0x00),
            NCSInstructionType.LOGANDII => (NCSByteCode.LOGANDxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.LOGORII => (NCSByteCode.LOGORxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.INCORII => (NCSByteCode.INCORxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.EXCORII => (NCSByteCode.EXCORxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.BOOLANDII => (NCSByteCode.BOOLANDxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.EQUALII => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.EQUALFF => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.EQUALSS => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.StringString),
            NCSInstructionType.EQUALOO => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.ObjectObject),
            NCSInstructionType.EQUALTT => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.StructStruct),
            NCSInstructionType.EQUALEFFEFF => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.EffectEffect),
            NCSInstructionType.EQUALEVTEVT => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.EventEvent),
            NCSInstructionType.EQUALLOCLOC => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.LocationLocation),
            NCSInstructionType.EQUALTALTAL => (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.TalentTalent),
            NCSInstructionType.NEQUALII => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.NEQUALFF => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.NEQUALSS => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.StringString),
            NCSInstructionType.NEQUALOO => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.ObjectObject),
            NCSInstructionType.NEQUALTT => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.StructStruct),
            NCSInstructionType.NEQUALEFFEFF => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.EffectEffect),
            NCSInstructionType.NEQUALEVTEVT => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.EventEvent),
            NCSInstructionType.NEQUALLOCLOC => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.LocationLocation),
            NCSInstructionType.NEQUALTALTAL => (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.TalentTalent),
            NCSInstructionType.GEQII => (NCSByteCode.GEQxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.GEQFF => (NCSByteCode.GEQxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.GTII => (NCSByteCode.GTxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.GTFF => (NCSByteCode.GTxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.LTII => (NCSByteCode.LTxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.LTFF => (NCSByteCode.LTxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.LEQII => (NCSByteCode.LEQxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.LEQFF => (NCSByteCode.LEQxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.SHLEFTII => (NCSByteCode.SHLEFTxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.SHRIGHTII => (NCSByteCode.SHRIGHTxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.USHRIGHTII => (NCSByteCode.USHRIGHTxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.ADDII => (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.ADDIF => (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.IntFloat),
            NCSInstructionType.ADDFI => (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.FloatInt),
            NCSInstructionType.ADDFF => (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.ADDSS => (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.StringString),
            NCSInstructionType.ADDVV => (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.VectorVector),
            NCSInstructionType.SUBII => (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.SUBIF => (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.IntFloat),
            NCSInstructionType.SUBFI => (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.FloatInt),
            NCSInstructionType.SUBFF => (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.SUBVV => (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.VectorVector),
            NCSInstructionType.MULII => (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.MULIF => (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.IntFloat),
            NCSInstructionType.MULFI => (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.FloatInt),
            NCSInstructionType.MULFF => (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.MULVF => (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.VectorFloat),
            NCSInstructionType.MULFV => (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.FloatVector),
            NCSInstructionType.DIVII => (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.DIVIF => (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.IntFloat),
            NCSInstructionType.DIVFI => (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.FloatInt),
            NCSInstructionType.DIVFF => (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.FloatFloat),
            NCSInstructionType.DIVVF => (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.VectorFloat),
            NCSInstructionType.DIVFV => (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.FloatVector),
            NCSInstructionType.MODII => (NCSByteCode.MODxx, (byte)NCSInstructionQualifier.IntInt),
            NCSInstructionType.NEGI => (NCSByteCode.NEGx, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.NEGF => (NCSByteCode.NEGx, (byte)NCSInstructionQualifier.Float),
            NCSInstructionType.COMPI => (NCSByteCode.COMPx, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.MOVSP => (NCSByteCode.MOVSP, 0x00),
            NCSInstructionType.JMP => (NCSByteCode.JMP, 0x00),
            NCSInstructionType.JSR => (NCSByteCode.JSR, 0x00),
            NCSInstructionType.JZ => (NCSByteCode.JZ, 0x00),
            NCSInstructionType.RETN => (NCSByteCode.RETN, 0x00),
            NCSInstructionType.DESTRUCT => (NCSByteCode.DESTRUCT, 0x01),
            NCSInstructionType.NOTI => (NCSByteCode.NOTx, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.DECxSP => (NCSByteCode.DECxSP, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.INCxSP => (NCSByteCode.INCxSP, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.JNZ => (NCSByteCode.JNZ, 0x00),
            NCSInstructionType.CPDOWNBP => (NCSByteCode.CPDOWNBP, 0x01),
            NCSInstructionType.CPTOPBP => (NCSByteCode.CPTOPBP, 0x01),
            NCSInstructionType.DECxBP => (NCSByteCode.DECxBP, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.INCxBP => (NCSByteCode.INCxBP, (byte)NCSInstructionQualifier.Int),
            NCSInstructionType.SAVEBP => (NCSByteCode.SAVEBP, 0x00),
            NCSInstructionType.RESTOREBP => (NCSByteCode.RESTOREBP, 0x00),
            NCSInstructionType.STORE_STATE => (NCSByteCode.STORE_STATE, 0x10),
            NCSInstructionType.NOP2 => (NCSByteCode.NOP2, 0x00),
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
        };
    }

    /// <summary>
    /// Create an NCSInstructionType from bytecode and qualifier.
    /// </summary>
    public static NCSInstructionType FromBytecode(NCSByteCode byteCode, byte qualifier)
    {
        return (byteCode, qualifier) switch
        {
            (NCSByteCode.RESERVED, 0x00) => NCSInstructionType.RESERVED,
            (NCSByteCode.RESERVED, 0x01) => NCSInstructionType.RESERVED_01,
            (NCSByteCode.NOP, 0x00) => NCSInstructionType.NOP,
            (NCSByteCode.CPDOWNSP, 0x01) => NCSInstructionType.CPDOWNSP,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.RSADDI,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Float) => NCSInstructionType.RSADDF,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.String) => NCSInstructionType.RSADDS,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Object) => NCSInstructionType.RSADDO,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Effect) => NCSInstructionType.RSADDEFF,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Event) => NCSInstructionType.RSADDEVT,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Location) => NCSInstructionType.RSADDLOC,
            (NCSByteCode.RSADDx, (byte)NCSInstructionQualifier.Talent) => NCSInstructionType.RSADDTAL,
            (NCSByteCode.CPTOPSP, 0x01) => NCSInstructionType.CPTOPSP,
            (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.CONSTI,
            (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.Float) => NCSInstructionType.CONSTF,
            (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.String) => NCSInstructionType.CONSTS,
            (NCSByteCode.CONSTx, (byte)NCSInstructionQualifier.Object) => NCSInstructionType.CONSTO,
            (NCSByteCode.ACTION, 0x00) => NCSInstructionType.ACTION,
            (NCSByteCode.LOGANDxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.LOGANDII,
            (NCSByteCode.LOGORxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.LOGORII,
            (NCSByteCode.INCORxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.INCORII,
            (NCSByteCode.EXCORxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.EXCORII,
            (NCSByteCode.BOOLANDxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.BOOLANDII,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.EQUALII,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.EQUALFF,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.StringString) => NCSInstructionType.EQUALSS,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.ObjectObject) => NCSInstructionType.EQUALOO,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.StructStruct) => NCSInstructionType.EQUALTT,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.EffectEffect) => NCSInstructionType.EQUALEFFEFF,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.EventEvent) => NCSInstructionType.EQUALEVTEVT,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.LocationLocation) => NCSInstructionType.EQUALLOCLOC,
            (NCSByteCode.EQUALxx, (byte)NCSInstructionQualifier.TalentTalent) => NCSInstructionType.EQUALTALTAL,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.NEQUALII,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.NEQUALFF,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.StringString) => NCSInstructionType.NEQUALSS,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.ObjectObject) => NCSInstructionType.NEQUALOO,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.StructStruct) => NCSInstructionType.NEQUALTT,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.EffectEffect) => NCSInstructionType.NEQUALEFFEFF,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.EventEvent) => NCSInstructionType.NEQUALEVTEVT,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.LocationLocation) => NCSInstructionType.NEQUALLOCLOC,
            (NCSByteCode.NEQUALxx, (byte)NCSInstructionQualifier.TalentTalent) => NCSInstructionType.NEQUALTALTAL,
            (NCSByteCode.GEQxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.GEQII,
            (NCSByteCode.GEQxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.GEQFF,
            (NCSByteCode.GTxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.GTII,
            (NCSByteCode.GTxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.GTFF,
            (NCSByteCode.LTxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.LTII,
            (NCSByteCode.LTxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.LTFF,
            (NCSByteCode.LEQxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.LEQII,
            (NCSByteCode.LEQxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.LEQFF,
            (NCSByteCode.SHLEFTxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.SHLEFTII,
            (NCSByteCode.SHRIGHTxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.SHRIGHTII,
            (NCSByteCode.USHRIGHTxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.USHRIGHTII,
            (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.ADDII,
            (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.IntFloat) => NCSInstructionType.ADDIF,
            (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.FloatInt) => NCSInstructionType.ADDFI,
            (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.ADDFF,
            (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.StringString) => NCSInstructionType.ADDSS,
            (NCSByteCode.ADDxx, (byte)NCSInstructionQualifier.VectorVector) => NCSInstructionType.ADDVV,
            (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.SUBII,
            (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.IntFloat) => NCSInstructionType.SUBIF,
            (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.FloatInt) => NCSInstructionType.SUBFI,
            (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.SUBFF,
            (NCSByteCode.SUBxx, (byte)NCSInstructionQualifier.VectorVector) => NCSInstructionType.SUBVV,
            (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.MULII,
            (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.IntFloat) => NCSInstructionType.MULIF,
            (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.FloatInt) => NCSInstructionType.MULFI,
            (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.MULFF,
            (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.VectorFloat) => NCSInstructionType.MULVF,
            (NCSByteCode.MULxx, (byte)NCSInstructionQualifier.FloatVector) => NCSInstructionType.MULFV,
            (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.DIVII,
            (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.IntFloat) => NCSInstructionType.DIVIF,
            (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.FloatInt) => NCSInstructionType.DIVFI,
            (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.FloatFloat) => NCSInstructionType.DIVFF,
            (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.VectorFloat) => NCSInstructionType.DIVVF,
            (NCSByteCode.DIVxx, (byte)NCSInstructionQualifier.FloatVector) => NCSInstructionType.DIVFV,
            (NCSByteCode.MODxx, (byte)NCSInstructionQualifier.IntInt) => NCSInstructionType.MODII,
            (NCSByteCode.NEGx, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.NEGI,
            (NCSByteCode.NEGx, (byte)NCSInstructionQualifier.Float) => NCSInstructionType.NEGF,
            (NCSByteCode.COMPx, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.COMPI,
            (NCSByteCode.MOVSP, 0x00) => NCSInstructionType.MOVSP,
            (NCSByteCode.JMP, 0x00) => NCSInstructionType.JMP,
            (NCSByteCode.JSR, 0x00) => NCSInstructionType.JSR,
            (NCSByteCode.JZ, 0x00) => NCSInstructionType.JZ,
            (NCSByteCode.RETN, 0x00) => NCSInstructionType.RETN,
            (NCSByteCode.DESTRUCT, 0x01) => NCSInstructionType.DESTRUCT,
            (NCSByteCode.NOTx, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.NOTI,
            (NCSByteCode.DECxSP, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.DECxSP,
            (NCSByteCode.INCxSP, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.INCxSP,
            (NCSByteCode.JNZ, 0x00) => NCSInstructionType.JNZ,
            (NCSByteCode.CPDOWNBP, 0x01) => NCSInstructionType.CPDOWNBP,
            (NCSByteCode.CPTOPBP, 0x01) => NCSInstructionType.CPTOPBP,
            (NCSByteCode.DECxBP, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.DECxBP,
            (NCSByteCode.INCxBP, (byte)NCSInstructionQualifier.Int) => NCSInstructionType.INCxBP,
            (NCSByteCode.SAVEBP, 0x00) => NCSInstructionType.SAVEBP,
            (NCSByteCode.RESTOREBP, 0x00) => NCSInstructionType.RESTOREBP,
            (NCSByteCode.STORE_STATE, 0x10) => NCSInstructionType.STORE_STATE,
            // Note: NOP2 has the same bytecode value (0x2D) as NOP, so it's handled by the NOP pattern above
            _ => throw new ArgumentException($"Unknown NCS instruction: bytecode=0x{(byte)byteCode:X2}, qualifier=0x{qualifier:X2}")
        };
    }
}

