using System.Collections.Generic;
using CSharpKOTOR.Common;
using CSharpKOTOR.Resource.Formats.GFF;
using JetBrains.Annotations;

namespace CSharpKOTOR.Resource.Generics
{
    /// <summary>
    /// Stores module information.
    ///
    /// IFO files are GFF-based format files that store module information including
    /// entry points, script hooks, area lists, and module metadata.
    /// </summary>
    [PublicAPI]
    public sealed class IFO
    {
        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:36
        // Original: BINARY_TYPE = ResourceType.IFO
        public static readonly ResourceType BinaryType = ResourceType.IFO;

        // Module ID: 16-byte unique identifier generated by toolset
        public byte[] ModId { get; set; } = new byte[16];

        // Localized module name displayed in-game
        public LocalizedString Name { get; set; } = LocalizedString.FromInvalid();

        // Module tag identifier
        public string Tag { get; set; } = string.Empty;

        // Entry area ResRef (starting area)
        public ResRef EntryArea { get; set; } = ResRef.FromInvalid();

        // Entry X position
        public float EntryX { get; set; }

        // Entry Y position
        public float EntryY { get; set; }

        // Entry Z position
        public float EntryZ { get; set; }

        // Entry direction (facing)
        public float EntryDirectionX { get; set; }
        public float EntryDirectionY { get; set; }
        public float EntryDirectionZ { get; set; }

        // Module script hooks
        public ResRef OnClientEnter { get; set; } = ResRef.FromInvalid();
        public ResRef OnClientLeave { get; set; } = ResRef.FromInvalid();
        public ResRef OnHeartbeat { get; set; } = ResRef.FromInvalid();
        public ResRef OnUserDefined { get; set; } = ResRef.FromInvalid();
        public ResRef OnActivateItem { get; set; } = ResRef.FromInvalid();
        public ResRef OnAcquireItem { get; set; } = ResRef.FromInvalid();
        public ResRef OnUnacquireItem { get; set; } = ResRef.FromInvalid();
        public ResRef OnPlayerDeath { get; set; } = ResRef.FromInvalid();
        public ResRef OnPlayerDying { get; set; } = ResRef.FromInvalid();
        public ResRef OnPlayerRespawn { get; set; } = ResRef.FromInvalid();
        public ResRef OnPlayerRest { get; set; } = ResRef.FromInvalid();
        public ResRef OnPlayerLevelUp { get; set; } = ResRef.FromInvalid();
        public ResRef OnPlayerCancelCutscene { get; set; } = ResRef.FromInvalid();

        // Area list (areas in this module)
        public List<ResRef> AreaList { get; set; } = new List<ResRef>();

        // Expansion pack requirements
        public int ExpansionPack { get; set; }

        // Module description
        public LocalizedString Description { get; set; } = LocalizedString.FromInvalid();

        // Module version
        public int ModVersion { get; set; }

        // Module Vault ID (for multiplayer)
        public int VaultId { get; set; }

        public IFO()
        {
        }
    }
}
